### PR TITLE
feat: create help page

### PR DESCRIPTION
**Pull request by reedwane**
- converted the previous faq component to be used in the help page.
- created needed components for the help page
- mimicked the search and implemented functions and validations

image

image

image

### CODE REVIEW

**Comment by reedwane** [comment]
image

Fixed

**Comment by arhziz** [comment]
> image
> Fixed

we should have a uniform color for the icons, the sending money icon color is black while the rest are gray, please fix that as well, also reduce its size a bit so as to match the rest

**Comment by reedwane** [comment]
> > image
> > Fixed
> 
> we should have a uniform color for the icons, the sending money icon color is black while the rest are gray, please fix that as well, also reduce its size a bit so as to match the rest

Will see to that now

**Comment by reedwane** [comment]
image


> > > image
> > > Fixed
> > 
> > 
> > we should have a uniform color for the icons, the sending money icon color is black while the rest are gray, please fix that as well, also reduce its size a bit so as to match the rest
> 
> Will see to that now

image

done

**Pull request merged**
